### ISSUE TITLE
Adding vertical panel support

### ISSUE THREAD

**Issue by luisbocanegra** [dhruv8sh/kara#1]
If you aren't working on it already, I can add vertical panel support

**Comment by dhruv8sh** [comment]
I'm halfway there, appreciate you asking for help.
I will definitely ask for help with something I know I will run into something later on.

**Comment by luisbocanegra** [comment]
My suggestion would be to convert the current item into a GridLayout and let the GridLayout items resize the grid as needed, no logic about placement would be needed

**Comment by dhruv8sh** [comment]
I did try that. I went through all of this trouble because ```GridLayout``` does not resize it's cells dynamically.
So many representations, especially the Pills would just not work with ```GridLayout```.

**Comment by luisbocanegra** [comment]
I got it working

**Comment by dhruv8sh** [comment]
Can I have a look?

**Comment by luisbocanegra** [comment]
https://github.com/luisbocanegra/kara/commit/b8fe40d4fa67843510c4f5f24bdb0e43e1f667de

**Comment by luisbocanegra** [comment]
Had to use a parent rectangle and update it from the Loader when height/width changes

**Comment by luisbocanegra** [comment]
Should the labels of the text indicator rotate for vertical panels?

![Screenshot_20240908_142252](https://github.com/user-attachments/assets/457090f6-eb62-40c8-8857-fa8642986250)

**Comment by dhruv8sh** [comment]
> Had to use a parent rectangle and update it from the Loader when height/width changes

That's very smart! I played around for a lot of time and just couldn't figure it out.

> Should the labels of the text indicator rotate for vertical panels?

Yes, I have added a config option for it. If they are using something simple like just the desktop number, they might not want to rotate it. I will merge your pull request and add in a few more things, then we can continue.

**Comment by dhruv8sh** [comment]
Vertical panel support was added.
I'll close this now, but we can use this thread for further discussions if you ever want to help out.
