### ISSUE TITLE
Structure kara configurations better

### ISSUE THREAD

**Issue by HeitorAugustoLN** [dhruv8sh/kara#11]
I think current options are quite a mess. The end-user will probably not care, but I think it should be structured in a better way.

Some examples:
  - Many options from **Text** indicator style are shared with **Icons** indicator style (I don't think they should be, because some user could want to use different options for each style, when switching from them)
  - **Don't change inactive pills** is technically for the **Pills** indicator style (it is what the name suggest), but the option is available in all indicator styles, and it is set `type2` group (which should be Text?)
  - Configuration groups don't have intuitive names (for example, `type1`, `type2`, etc.). They should probably have their indicator style name such as `pills`, `text` and `icons`

**Comment by dhruv8sh** [comment]
They are, aren't they. There is something in the works already but I just got my first job. Kara will get an update on the first holiday I get(Sunday).

**Comment by dhruv8sh** [comment]
Latest commit makes this better, please review it.
If you have any other ideas in mind let me know.

**Comment by HeitorAugustoLN** [comment]
Thanks for the update! It looks really better now.
