### ISSUE TITLE
Incorrectly placed animation with pill pager style on desktop grid layout.

### ISSUE THREAD

**Issue by arklese1zure** [dhruv8sh/kara#3]
Steps to replicate behavior:
- Virtual desktops are in a 2x2 grid configuration.
- Desktop is switched with a trackpad gesture (horizontally works fine, but vertically doesn't).
- The above also happens when clicking on a vertically adjacent desktop.
- The behavior does not appear when scrolling directly on the widget.

Some specs:
- Arch linux running 6.10.6-arch1-1
- Plasma 6.1.4
- Running latest 0.1 hotfix

Attached screenshot:
![2024-09-09_16-20](https://github.com/user-attachments/assets/645df599-74f4-4a50-a0bd-e107a8849c58)
Let me know if you need any more info.

**Comment by dhruv8sh** [comment]
This was already fixed in the last commit.
I got a bit busy, the next release should be out tomorrow.
