### ISSUE TITLE
Click to switch desktop broken

### ISSUE THREAD

**Issue by luisbocanegra** [dhruv8sh/kara#6]
After https://github.com/dhruv8sh/kara/releases/tag/v0.7 the click to switch desktop no longer works, I am not sure what changed but apparently the MouseArea in the HighlightLoader is blocking the event

https://github.com/dhruv8sh/kara/blob/e289644c8478bb93f1f7c289dda380d00c237897/contents/ui/Common/HighlightLoader.qml#L34

https://github.com/dhruv8sh/kara/blob/e289644c8478bb93f1f7c289dda380d00c237897/contents/ui/representations/TextStyle.qml#L38

Tried making it reject the clicks and propagate them but the problem persists

```qml
MouseArea {
        id: mouseArea
        anchors.fill: parent
        hoverEnabled: cfg.highlightOnHover
        onEntered: op = 0.4
        onExited: op = calcOp()
        propagateComposedEvents: true
        onClicked: (mouse) =>{
            console.error("onClicked")
            mouse.accepted = false
        }
    }
```

**Comment by dhruv8sh** [comment]
Yes, of course it does. Did not test this.

Would be a better decision to leave the mousearea there and remove the taphandler and

**Comment by luisbocanegra** [comment]
Hmm maybe, I think it would be best to move all the logic to the reptRect and leave visuals to Style and highlight

**Comment by dhruv8sh** [comment]
Yes that makes a lot of sense. I'll do it.

I have a couple issues in mind if you could help with them.
For the addAsterisk option: Whenever I open a window, the slight delay before the window pops up, the asterisk is shown for all desktops. It should only show when that desktop contains an active window.

I also need help with writing a representation which shows the icons of the windows open in that desktop, clickable preferably, I have had a couple of iterations and they did not go great.

**Comment by luisbocanegra** [comment]
Sure I can take a look, I'll let you know if I do and manage to get something working

**Comment by luisbocanegra** [comment]
> I have a couple issues in mind if you could help with them.
> For the addAsterisk option: Whenever I open a window, the slight delay before the window pops up, the asterisk is shown for all desktops. It should only show when that desktop contains an active window.

Managed to fix that one https://github.com/dhruv8sh/kara/pull/8, not sure if it's the best approach but seems to be working on wayland.

Now there is even more duplicate code so it's okay if you want to work on moving the logic first and I will update the patch later
