### ISSUE TITLE
Can't remove plasmoid

### ISSUE THREAD

**Issue by AndydeCleyre** [dhruv8sh/kara#9]
Hello!

I didn't see anything about a minimum Plasma version, so though I realized it was unlikely to be supported on my ancient `5.24.7`, I installed it via `install.sh` to see for myself. 

I added it to my panel, but it doesn't work (configure button has no action, right click seems to go through to the panel itself, and it appears as just a wide empty space).

So I enter the panel's edit mode, which offers me the Configure and Alternatives buttons, but no remove button.

**Comment by dhruv8sh** [comment]
Ahh yes! I should add to the Readme that it's for Plasma 6.
You can just remove the folder ~/.local/share/plasma/plasmoids/org.dhruv8sh.kara
